[workspace]
members = [
  "minidodo-cli",
  "minidodo-core",
  "minidodo-infra",
  "minidodo-server",
  "minidodo-psp",
  "minidodo-worker",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"

[profile.dev]
incremental = true
opt-level = 0

[profile.dev.package."*"]
opt-level = 1

[workspace.dependencies]
tokio = { version = "1.40", features = ["full"] }
axum = { version = "0.8.6" }
tower = { version = "0.5.2" }
tower-layer = "0.3.3"
tower-http = { version = "0.6.6", features = ["trace", "cors", "normalize-path"] }
sqlx = { version = "0.8.6", features = [
  "postgres",
  "chrono",
  "uuid",
  "runtime-tokio",
  "migrate",
] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
uuid = { version = "1.18.0", features = ["serde", "v4"] }
chrono = { version = "0.4.41", features = ["serde"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = [
  "registry",
  "env-filter",
  "json",
] }
snafu = "0.8.4"
validator = { version = "0.20", features = ["derive"] }
sha2 = "0.10.8"
dotenvy = "0.15.7"

minidodo-core = { path = "minidodo-core" }
minidodo-infra = { path = "minidodo-infra" }
minidodo-server = { path = "minidodo-server" }
minidodo-psp = { path = "minidodo-psp" }
minidodo-worker = { path = "minidodo-worker" }
