[package]
name = "minidodo-core"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
snafu = { workspace = true }
axum = { workspace = true }
sqlx = { workspace = true }
utoipa = { version = "5.3.1", features = ["axum_extras", "chrono", "uuid"] }
validator = { workspace = true }
tracing = { workspace = true }
figment = { version = "0.10.19", features = ["env"] }
sha2 = { workspace = true }
hmac = { workspace = true }
hex = { workspace = true }
subtle = "2.6.1"
