[package]
name = "minidodo-core"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
axum = { workspace = true }
utoipa = { workspace = true }
validator = { workspace = true }
tracing = { workspace = true }
figment = { workspace = true }
uncased = { workspace = true }
