[package]
name = "minidodo-server"
version.workspace = true
edition.workspace = true

[dependencies]
minidodo-core = { workspace = true }
minidodo-infra = { workspace = true }
tokio = { workspace = true }
axum = { workspace = true }
tower = { workspace = true }
tower-layer = { workspace = true }
tower-http = { workspace = true }
utoipa = { version = "5.3.1", features = ["axum_extras", "chrono", "uuid"] }
utoipa-swagger-ui = { version = "9.0.0", features = ["axum", "vendored", "debug-embed"] }
validator = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
sha2 = { workspace = true }
hex = "0.4.3"
